In [68]:
import pandas as pd
import sqlite3

In [69]:
pd.reset_option("display.max_rows")

In [79]:
# pd.set_option("display.max_rows", None)
conn = sqlite3.connect('data/charts-sea.db')
cursor = conn.cursor()
pd.read_sql_query("SELECT * FROM track_data", conn)

,id,track_id,track_name,artist_id,artist_name,album_id,duration,release_date,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,1,5MJgMHroAGmTvMN2Q1aCNH,umakeme,09TbfG9329V26zqpb7IQT5,Xuân Nghi,6mXug47jOXJs8hgf4ra0MD,247764,2018-03-01,0,0.646,0.359,10,-12.030,1,0.1230,0.89900,0.046500,0.2860,0.4300,84.964
1,2,5xOkL4eAs735nm6mcnvfS6,#AiChoAi,25cLQ8alZJssXY06KE3SZP,Flo D,2LIIs10mS32UD5suD6CtHA,159973,2016-04-24,38,0.730,0.316,6,-10.632,1,0.0428,0.91700,0.000343,0.1110,0.7130,117.952
2,3,1L9obzxoUqbYVxTqbGBS6O,#Glaiter,32vpj3OfAguCApf3kgX6Hi,VKL,0S8yyxd4VK7GpfAuu3P3EN,270914,2018-10-12,1,0.750,0.762,0,-6.950,1,0.1520,0.55400,0.000000,0.0820,0.3990,138.032
3,4,64kbi0kNr7D5IzwpOVPXe4,#IDONTNEEDNOPETERPANTOSHOWMEWHATTODO,4nWIpSNa5qWt5IKinzX3fr,Quarterjack,5CmBMusAOfo5bFh7aUepel,127792,2018-02-02,0,0.617,0.445,5,-8.942,0,0.0578,0.00546,0.986000,0.1280,0.0487,124.023
4,5,663hJaCpsyLwUGqj7TEXRZ,#คนเหงา2018,78TMykAte8FKWQ3f6cQBol,Point,7HtJdFnKVBD04TtSDWjFnB,271442,2018-02-26,5,0.782,0.674,11,-6.195,1,0.0270,0.58800,0.000746,0.2100,0.7270,104.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15642,15643,4dwwfiOzRNlKNUSgfx4Z2k,Outta My Head,7zYj9S9SdIunYCfSm7vzAR,JEON SOMI,7GfqgsiW63VBNLRvIrhqLx,188161,2019-06-13,0,0.718,0.488,3,-6.930,1,0.0530,0.38800,0.000000,0.3730,0.5800,130.048
15643,15644,3XzxHvEomjJIKZcZqYfFut,운명 The Chance of Love,6nVMMEywS5Y4tsHPKx1nIo,TVXQ!,0ipyHYAE0cMf4aDJNIDIU1,207133,2018-03-28,47,0.784,0.721,6,-2.571,0,0.0453,0.15400,0.000000,0.2380,0.9150,112.013
15644,15645,3DGKXLtVjawKFweymvHn84,키스는 다음에,52zMTJCKluDlFwMQWmccY7,LOONA,7j4J6jWNmKjzpiWxPEdEcS,199754,2017-01-16,51,0.412,0.767,11,-4.108,1,0.0914,0.17600,0.000000,0.0733,0.6340,207.437
15645,15646,2AA1f7utyvXpmtKsEvp5lz,하루살이,3eCd0TZrBPm2n9cDG6yWfF,DEAN,7Jx4yrb93ioommudLfYAx8,207112,2018-11-09,61,0.726,0.492,10,-8.046,0,0.0794,0.56600,0.000008,0.2570,0.5260,85.939
15646,15647,4mYu3kfBCW6qiTDnfVeuMx,항상 (HANGSANG),0b1sIQumIAsNbqAoIClSpy,j-hope,1bJ8O4jIyqSdunqT9RWXc9,229675,2018-03-02,0,0.832,0.896,6,-4.673,1,0.2330,0.15900,0.000048,0.2470,0.6180,178.998

In [71]:
# pd.read_sql_query("DROP TABLE track_data", conn)

In [72]:
region_tables = pd.read_sql_query("SELECT * FROM sqlite_master where type='table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '%track_data';", conn)["name"]

In [73]:
charts_sea_df = pd.DataFrame()

for region in region_tables:
    charts_sea_df = charts_sea_df.append(pd.read_sql_query("SELECT * FROM " + region, conn))

C:\Users\moshpit_yoshi\AppData\Local\Temp\ipykernel_11068\1233094731.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  charts_sea_df = charts_sea_df.append(pd.read_sql_query("SELECT * FROM " + region, conn))
C:\Users\moshpit_yoshi\AppData\Local\Temp\ipykernel_11068\1233094731.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  charts_sea_df = charts_sea_df.append(pd.read_sql_query("SELECT * FROM " + region, conn))
C:\Users\moshpit_yoshi\AppData\Local\Temp\ipykernel_11068\1233094731.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  charts_sea_df = charts_sea_df.append(pd.read_sql_query("SELECT * FROM " + region, conn))
C:\Users\moshpit_yoshi\AppData\Local\Temp\ipykernel_11068\1233094731.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  charts_sea_df = charts_sea_df.append(pd.read_sql_query("SELECT * FROM " + region, conn))
C:\Users\moshpit_yoshi\AppData\Local\Temp\ipykernel_11068\1233094731.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  charts_sea_df = charts_sea_df.append(pd.read_sql_query("SELECT * FROM " + region, conn))
C:\Users\moshpit_yoshi\AppData\Local\Temp\ipykernel_11068\1233094731.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  charts_sea_df = charts_sea_df.append(pd.read_sql_query("SELECT * FROM " + region, conn))

In [74]:
charts_sea_df.drop('id', axis=1).duplicated().sum()

0

In [75]:
charts_sea_df["date"].min()

'2017-01-01'

In [76]:
charts_sea_df["date"].max()

'2023-09-07'

In [80]:
conn.close()